// <auto-generated />
using System;
using Infraestrutura.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestrutura.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dominio.Persistencia.Carrapato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoSerial")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<int>("IdPatio")
                        .HasColumnType("int");

                    b.Property<int>("StatusBateria")
                        .HasColumnType("int");

                    b.Property<int>("StatusDeUso")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CodigoSerial")
                        .IsUnique();

                    b.HasIndex("IdPatio");

                    b.ToTable("CARRAPATOS", (string)null);
                });

            modelBuilder.Entity("Dominio.Persistencia.Moto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Chassi")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<int>("IdCarrapato")
                        .HasColumnType("int");

                    b.Property<int>("IdPatio")
                        .HasColumnType("int");

                    b.Property<int>("Modelo")
                        .HasColumnType("int");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<int>("Zona")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Chassi")
                        .IsUnique();

                    b.HasIndex("IdCarrapato")
                        .IsUnique();

                    b.HasIndex("IdPatio");

                    b.HasIndex("Placa")
                        .IsUnique();

                    b.ToTable("MOTOS", (string)null);
                });

            modelBuilder.Entity("Dominio.Persistencia.Mottu.MotoMottu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_MOTO");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Chassi")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)")
                        .HasColumnName("CHASSI");

                    b.Property<int>("Modelo")
                        .HasColumnType("int")
                        .HasColumnName("ID_MODELO");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasColumnName("PLACA");

                    b.HasKey("Id");

                    b.ToTable("MOTOS_MOTTU", (string)null);
                });

            modelBuilder.Entity("Dominio.Persistencia.Patio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("PATIOS", (string)null);
                });

            modelBuilder.Entity("Dominio.Persistencia.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IdPatio")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdPatio");

                    b.ToTable("USUARIOS", (string)null);
                });

            modelBuilder.Entity("Dominio.Persistencia.Carrapato", b =>
                {
                    b.HasOne("Dominio.Persistencia.Patio", "Patio")
                        .WithMany("Carrapatos")
                        .HasForeignKey("IdPatio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patio");
                });

            modelBuilder.Entity("Dominio.Persistencia.Moto", b =>
                {
                    b.HasOne("Dominio.Persistencia.Carrapato", "Carrapato")
                        .WithOne("MotoVinculada")
                        .HasForeignKey("Dominio.Persistencia.Moto", "IdCarrapato")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dominio.Persistencia.Patio", "Patio")
                        .WithMany("Motos")
                        .HasForeignKey("IdPatio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Carrapato");

                    b.Navigation("Patio");
                });

            modelBuilder.Entity("Dominio.Persistencia.Usuario", b =>
                {
                    b.HasOne("Dominio.Persistencia.Patio", "Patio")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdPatio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patio");
                });

            modelBuilder.Entity("Dominio.Persistencia.Carrapato", b =>
                {
                    b.Navigation("MotoVinculada")
                        .IsRequired();
                });

            modelBuilder.Entity("Dominio.Persistencia.Patio", b =>
                {
                    b.Navigation("Carrapatos");

                    b.Navigation("Motos");

                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
