-- ============================================================================
-- DDL para Sistema de Gerenciamento de Motos Mottu - SQL SERVER
-- ============================================================================

-- Verificar se as tabelas já existem e limpar se necessário
IF OBJECT_ID('dbo.MOTOS_MOTTU', 'U') IS NOT NULL DROP TABLE MOTOS_MOTTU;
IF OBJECT_ID('dbo.MODELOS_MOTO_MOTTU', 'U') IS NOT NULL DROP TABLE MODELOS_MOTO_MOTTU;
IF OBJECT_ID('dbo.MOTOS', 'U') IS NOT NULL DROP TABLE MOTOS;
IF OBJECT_ID('dbo.CARRAPATOS', 'U') IS NOT NULL DROP TABLE CARRAPATOS;
IF OBJECT_ID('dbo.USUARIOS', 'U') IS NOT NULL DROP TABLE USUARIOS;
IF OBJECT_ID('dbo.PATIOS', 'U') IS NOT NULL DROP TABLE PATIOS;

-- Criação das tabelas principais
-- ============================================================================

-- Tabela de Pátios
CREATE TABLE PATIOS (
    Id INT IDENTITY(1,1),
    Nome NVARCHAR(100) NOT NULL,
    Endereco NVARCHAR(255) NOT NULL,
    CONSTRAINT PK_Patios PRIMARY KEY (Id)
);

-- Tabela de Usuários
CREATE TABLE USUARIOS (
    Id INT IDENTITY(1,1),
    Email NVARCHAR(255) NOT NULL UNIQUE,
    Nome NVARCHAR(100) NOT NULL,
    Senha NVARCHAR(255) NOT NULL,
    DataCriacao DATETIME NOT NULL,
    IdPatio INT NOT NULL,
    CONSTRAINT PK_Usuarios PRIMARY KEY (Id),
    CONSTRAINT FK_Usuarios_Patio FOREIGN KEY (IdPatio) REFERENCES PATIOS(Id)
);

-- Tabela de Carrapatos 
CREATE TABLE CARRAPATOS (
    Id INT IDENTITY(1,1),
    CodigoSerial NVARCHAR(7) NOT NULL UNIQUE,
    StatusBateria INT NOT NULL, -- 0=Baixa, 1=Media, 2=Alta
    StatusDeUso INT NOT NULL,   -- 0=Disponivel, 1=EmUso, 2=Manutencao
    IdPatio INT NOT NULL,
    CONSTRAINT PK_Carrapatos PRIMARY KEY (Id),
    CONSTRAINT FK_Carrapatos_Patio FOREIGN KEY (IdPatio) REFERENCES PATIOS(Id),
    CONSTRAINT CK_Carrapatos_StatusBateria CHECK (StatusBateria IN (0, 1, 2)),
    CONSTRAINT CK_Carrapatos_StatusDeUso CHECK (StatusDeUso IN (0, 1, 2))
);

-- Tabela de Motos - Placa máximo 7 caracteres, Chassi máximo 17
CREATE TABLE MOTOS (
    Id INT IDENTITY(1,1),
    Placa NVARCHAR(7) NOT NULL UNIQUE,
    Chassi NVARCHAR(17) NOT NULL UNIQUE,
    Modelo INT NOT NULL, -- Enum do ModeloMotoEnum
    Zona INT NOT NULL,   -- Enum do ZonaEnum
    IdPatio INT NOT NULL,
    IdCarrapato INT NOT NULL,
    CONSTRAINT PK_Motos PRIMARY KEY (Id),
    CONSTRAINT FK_Motos_Patio FOREIGN KEY (IdPatio) REFERENCES PATIOS(Id),
    CONSTRAINT FK_Motos_Carrapato FOREIGN KEY (IdCarrapato) REFERENCES CARRAPATOS(Id)
);

-- Tabela de Modelos de Moto Mottu
CREATE TABLE MODELOS_MOTO_MOTTU (
    ID_MODELO INT IDENTITY(1,1),
    NOME_MODELO NVARCHAR(50) NOT NULL UNIQUE,
    CONSTRAINT PK_MODELO_MOTO PRIMARY KEY (ID_MODELO)
);

-- Tabela de Motos Mottu
CREATE TABLE MOTOS_MOTTU (
    ID_MOTO INT IDENTITY(1,1),
    CHASSI NVARCHAR(17) NOT NULL UNIQUE,
    PLACA NVARCHAR(7) NOT NULL UNIQUE,
    ID_MODELO INT NOT NULL,
    CONSTRAINT PK_MOTOS_MOTTU PRIMARY KEY (ID_MOTO),
    CONSTRAINT FK_MOTOS_MODELO FOREIGN KEY (ID_MODELO) REFERENCES MODELOS_MOTO_MOTTU(ID_MODELO)
);

-- ============================================================================
-- Inserção de dados de teste
-- ============================================================================

-- Inserção de Pátios (12 registros)
INSERT INTO PATIOS (Nome, Endereco) VALUES (N'Pátio Central SP', N'Rua da Consolação, 1000, São Paulo, SP');
INSERT INTO PATIOS (Nome, Endereco) VALUES (N'Pátio Zona Sul RJ', N'Av. Copacabana, 500, Rio de Janeiro, RJ');
INSERT INTO PATIOS (Nome, Endereco) VALUES (N'Pátio Norte BH', N'Rua dos Caetés, 200, Belo Horizonte, MG');
INSERT INTO PATIOS (Nome, Endereco) VALUES (N'Pátio Leste Salvador', N'Av. Sete de Setembro, 800, Salvador, BA');
INSERT INTO PATIOS (Nome, Endereco) VALUES (N'Pátio Centro Curitiba', N'Rua XV de Novembro, 300, Curitiba, PR');
INSERT INTO PATIOS (Nome, Endereco) VALUES (N'Pátio Sul Porto Alegre', N'Av. Borges de Medeiros, 600, Porto Alegre, RS');
INSERT INTO PATIOS (Nome, Endereco) VALUES (N'Pátio Oeste Brasília', N'SQN 106, Bloco A, Brasília, DF');
INSERT INTO PATIOS (Nome, Endereco) VALUES (N'Pátio Centro Recife', N'Rua do Bom Jesus, 150, Recife, PE');
INSERT INTO PATIOS (Nome, Endereco) VALUES (N'Pátio Norte Fortaleza', N'Av. Beira Mar, 1200, Fortaleza, CE');
INSERT INTO PATIOS (Nome, Endereco) VALUES (N'Pátio Sul Florianópolis', N'Rua Felipe Schmidt, 400, Florianópolis, SC');
INSERT INTO PATIOS (Nome, Endereco) VALUES (N'Pátio Centro Manaus', N'Av. Eduardo Ribeiro, 700, Manaus, AM');
INSERT INTO PATIOS (Nome, Endereco) VALUES (N'Pátio Leste Goiânia', N'Rua T-23, 350, Goiânia, GO');

-- Inserção de Usuários (12 registros)
INSERT INTO USUARIOS (Email, Nome, Senha, DataCriacao, IdPatio) VALUES (N'admin@mottu.com', N'Administrador Sistema', N'admin123', GETDATE(), 1);
INSERT INTO USUARIOS (Email, Nome, Senha, DataCriacao, IdPatio) VALUES (N'joao.silva@mottu.com', N'João Silva', N'senha123', GETDATE(), 1);
INSERT INTO USUARIOS (Email, Nome, Senha, DataCriacao, IdPatio) VALUES (N'maria.santos@mottu.com', N'Maria Santos', N'senha456', GETDATE(), 2);
INSERT INTO USUARIOS (Email, Nome, Senha, DataCriacao, IdPatio) VALUES (N'pedro.oliveira@mottu.com', N'Pedro Oliveira', N'senha789', GETDATE(), 3);
INSERT INTO USUARIOS (Email, Nome, Senha, DataCriacao, IdPatio) VALUES (N'ana.costa@mottu.com', N'Ana Costa', N'senha321', GETDATE(), 4);
INSERT INTO USUARIOS (Email, Nome, Senha, DataCriacao, IdPatio) VALUES (N'carlos.lima@mottu.com', N'Carlos Lima', N'senha654', GETDATE(), 5);
INSERT INTO USUARIOS (Email, Nome, Senha, DataCriacao, IdPatio) VALUES (N'lucia.ferreira@mottu.com', N'Lúcia Ferreira', N'senha987', GETDATE(), 6);
INSERT INTO USUARIOS (Email, Nome, Senha, DataCriacao, IdPatio) VALUES (N'marcos.almeida@mottu.com', N'Marcos Almeida', N'senha111', GETDATE(), 7);
INSERT INTO USUARIOS (Email, Nome, Senha, DataCriacao, IdPatio) VALUES (N'patricia.rocha@mottu.com', N'Patrícia Rocha', N'senha222', GETDATE(), 8);
INSERT INTO USUARIOS (Email, Nome, Senha, DataCriacao, IdPatio) VALUES (N'roberto.cunha@mottu.com', N'Roberto Cunha', N'senha333', GETDATE(), 9);
INSERT INTO USUARIOS (Email, Nome, Senha, DataCriacao, IdPatio) VALUES (N'fernanda.dias@mottu.com', N'Fernanda Dias', N'senha444', GETDATE(), 10);
INSERT INTO USUARIOS (Email, Nome, Senha, DataCriacao, IdPatio) VALUES (N'gabriel.reis@mottu.com', N'Gabriel Reis', N'senha555', GETDATE(), 11);

-- Inserção de Carrapatos (15 registros) - CodigoSerial limitado a 7 caracteres
INSERT INTO CARRAPATOS (CodigoSerial, StatusBateria, StatusDeUso, IdPatio) VALUES (N'GPS001', 2, 0, 1); -- Alta, Disponível
INSERT INTO CARRAPATOS (CodigoSerial, StatusBateria, StatusDeUso, IdPatio) VALUES (N'GPS002', 2, 1, 1); -- Alta, Em Uso
INSERT INTO CARRAPATOS (CodigoSerial, StatusBateria, StatusDeUso, IdPatio) VALUES (N'GPS003', 1, 0, 2); -- Média, Disponível
INSERT INTO CARRAPATOS (CodigoSerial, StatusBateria, StatusDeUso, IdPatio) VALUES (N'GPS004', 2, 0, 2); -- Alta, Disponível
INSERT INTO CARRAPATOS (CodigoSerial, StatusBateria, StatusDeUso, IdPatio) VALUES (N'GPS005', 0, 2, 3); -- Baixa, Manutenção
INSERT INTO CARRAPATOS (CodigoSerial, StatusBateria, StatusDeUso, IdPatio) VALUES (N'GPS006', 2, 1, 3); -- Alta, Em Uso
INSERT INTO CARRAPATOS (CodigoSerial, StatusBateria, StatusDeUso, IdPatio) VALUES (N'GPS007', 1, 0, 4); -- Média, Disponível
INSERT INTO CARRAPATOS (CodigoSerial, StatusBateria, StatusDeUso, IdPatio) VALUES (N'GPS008', 2, 0, 4); -- Alta, Disponível
INSERT INTO CARRAPATOS (CodigoSerial, StatusBateria, StatusDeUso, IdPatio) VALUES (N'GPS009', 1, 1, 5); -- Média, Em Uso
INSERT INTO CARRAPATOS (CodigoSerial, StatusBateria, StatusDeUso, IdPatio) VALUES (N'GPS010', 2, 0, 5); -- Alta, Disponível
INSERT INTO CARRAPATOS (CodigoSerial, StatusBateria, StatusDeUso, IdPatio) VALUES (N'GPS011', 2, 0, 6); -- Alta, Disponível
INSERT INTO CARRAPATOS (CodigoSerial, StatusBateria, StatusDeUso, IdPatio) VALUES (N'GPS012', 1, 2, 6); -- Média, Manutenção
INSERT INTO CARRAPATOS (CodigoSerial, StatusBateria, StatusDeUso, IdPatio) VALUES (N'GPS013', 2, 1, 7); -- Alta, Em Uso
INSERT INTO CARRAPATOS (CodigoSerial, StatusBateria, StatusDeUso, IdPatio) VALUES (N'GPS014', 0, 0, 7); -- Baixa, Disponível
INSERT INTO CARRAPATOS (CodigoSerial, StatusBateria, StatusDeUso, IdPatio) VALUES (N'GPS015', 2, 0, 8); -- Alta, Disponível

-- Inserção de Motos (15 registros) - Placas limitadas a 7 caracteres
INSERT INTO MOTOS (Placa, Chassi, Modelo, Zona, IdPatio, IdCarrapato) VALUES (N'ABC1234', N'9BWHE21JX24060831', 0, 0, 1, 1);
INSERT INTO MOTOS (Placa, Chassi, Modelo, Zona, IdPatio, IdCarrapato) VALUES (N'DEF5678', N'9BWHE21JX24060832', 1, 1, 1, 2);
INSERT INTO MOTOS (Placa, Chassi, Modelo, Zona, IdPatio, IdCarrapato) VALUES (N'GHI9012', N'9BWHE21JX24060833', 2, 0, 2, 3);
INSERT INTO MOTOS (Placa, Chassi, Modelo, Zona, IdPatio, IdCarrapato) VALUES (N'JKL3456', N'9BWHE21JX24060834', 0, 2, 2, 4);
INSERT INTO MOTOS (Placa, Chassi, Modelo, Zona, IdPatio, IdCarrapato) VALUES (N'MNO7890', N'9BWHE21JX24060835', 1, 1, 3, 5);
INSERT INTO MOTOS (Placa, Chassi, Modelo, Zona, IdPatio, IdCarrapato) VALUES (N'PQR1234', N'9BWHE21JX24060836', 2, 0, 3, 6);
INSERT INTO MOTOS (Placa, Chassi, Modelo, Zona, IdPatio, IdCarrapato) VALUES (N'STU5678', N'9BWHE21JX24060837', 0, 2, 4, 7);
INSERT INTO MOTOS (Placa, Chassi, Modelo, Zona, IdPatio, IdCarrapato) VALUES (N'VWX9012', N'9BWHE21JX24060838', 1, 1, 4, 8);
INSERT INTO MOTOS (Placa, Chassi, Modelo, Zona, IdPatio, IdCarrapato) VALUES (N'YZA3456', N'9BWHE21JX24060839', 2, 0, 5, 9);
INSERT INTO MOTOS (Placa, Chassi, Modelo, Zona, IdPatio, IdCarrapato) VALUES (N'BCD7890', N'9BWHE21JX24060840', 0, 2, 5, 10);
INSERT INTO MOTOS (Placa, Chassi, Modelo, Zona, IdPatio, IdCarrapato) VALUES (N'EFG1234', N'9BWHE21JX24060841', 1, 1, 6, 11);
INSERT INTO MOTOS (Placa, Chassi, Modelo, Zona, IdPatio, IdCarrapato) VALUES (N'HIJ5678', N'9BWHE21JX24060842', 2, 0, 6, 12);
INSERT INTO MOTOS (Placa, Chassi, Modelo, Zona, IdPatio, IdCarrapato) VALUES (N'KLM9012', N'9BWHE21JX24060843', 0, 2, 7, 13);
INSERT INTO MOTOS (Placa, Chassi, Modelo, Zona, IdPatio, IdCarrapato) VALUES (N'NOP3456', N'9BWHE21JX24060844', 1, 1, 7, 14);
INSERT INTO MOTOS (Placa, Chassi, Modelo, Zona, IdPatio, IdCarrapato) VALUES (N'QRS7890', N'9BWHE21JX24060845', 2, 0, 8, 15);

-- Inserção de Modelos de Moto Mottu (10 registros únicos)
INSERT INTO MODELOS_MOTO_MOTTU (NOME_MODELO) VALUES (N'SPORT');
INSERT INTO MODELOS_MOTO_MOTTU (NOME_MODELO) VALUES (N'E');
INSERT INTO MODELOS_MOTO_MOTTU (NOME_MODELO) VALUES (N'POP');
INSERT INTO MODELOS_MOTO_MOTTU (NOME_MODELO) VALUES (N'CLASSIC');
INSERT INTO MODELOS_MOTO_MOTTU (NOME_MODELO) VALUES (N'URBAN');
INSERT INTO MODELOS_MOTO_MOTTU (NOME_MODELO) VALUES (N'ECO');
INSERT INTO MODELOS_MOTO_MOTTU (NOME_MODELO) VALUES (N'PREMIUM');
INSERT INTO MODELOS_MOTO_MOTTU (NOME_MODELO) VALUES (N'DELIVERY');
INSERT INTO MODELOS_MOTO_MOTTU (NOME_MODELO) VALUES (N'TOURING');
INSERT INTO MODELOS_MOTO_MOTTU (NOME_MODELO) VALUES (N'COMPACT');

-- Inserção de Motos Mottu (120+ registros) - Chassi únicos garantidos
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'6Q6R6S7T7U7V7W8X8', N'RAB9C47', 1);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'1W8Y9Z0A1B2C3D4E5', N'JAZ6E29', 2);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'7F8G9H0I1J2K3L4M5', N'KBC7F13', 3);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'2N3P4Q5R6S7T8U9V0', N'MNC8G24', 4);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'8W9X0Y1Z2A3B4C5D6', N'PDR9H35', 5);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'3E4F5G6H7I8J9K0L1', N'QES0I46', 6);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'9M0N1P2Q3R4S5T6U7', N'TFU1J57', 7);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'4V5W6X7Y8Z9A0B1C2', N'VGU2K68', 8);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'0D1E2F3G4H5I6J7K8', N'WII3L79', 9);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'5L6M7N8P9Q0R1S2T3', N'XJJ4M80', 10);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'1U2V3W4X5Y6Z7A8B9', N'YKK5N91', 1);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'6C7D8E9F0G1H2I3J4', N'ZLL6O02', 2);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'2K3L4M5N6P7Q8R9S0', N'AMA7P13', 3);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'7T8U9V0W1X2Y3Z4A5', N'BNB8Q24', 4);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'3B4C5D6E7F8G9H0I1', N'COC9R35', 5);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'9J0K1L2M3N4P5Q6R7', N'DOD0S46', 6);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'4S5T6U7V8W9X0Y1Z2', N'EPE1T57', 7);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'0A1B2C3D4E5F6G7H8', N'FQF2U68', 8);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'5I6J7K8L9M0N1P2Q3', N'GRG3V79', 9);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'1R2S3T4U5V6W7X8Y9', N'HSH4W80', 10);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'6Z7A8B9C0D1E2F3G4', N'ITI5X91', 1);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'2H3I4J5K6L7M8N9P0', N'JTK6Y02', 2);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'7Q8R9S0T1U2V3W4X5', N'KUL7Z13', 3);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'3Y4Z5A6B7C8D9E0F1', N'LVM8A24', 4);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'9G0H1I2J3K4L5M6N7', N'MWN9B35', 5);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'4P5Q6R7S8T9U0V1W2', N'OXP0C46', 6);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'0X1Y2Z3A4B5C6D7E8', N'QYQ1D57', 7);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'5F6G7H8I9J0K1L2M3', N'SZR2E68', 8);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'1N2P3Q4R5S6T7U8V9', N'TAB3F79', 9);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'6W7X8Y9Z0A1B2C3D4', N'UBC4G80', 10);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'2E3F4G5H6I7J8K9L0', N'VCD5H91', 1);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'7M8N9P0Q1R2S3T4U5', N'WDE6I02', 2);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'3V4W5X6Y7Z8A9B0C1', N'XEF7J13', 3);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'8D9E0F1G2H3I4J5K6', N'YFG8K24', 4);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'4L5M6N7P8Q9R0S1T2', N'ZGH9L35', 5);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'0U1V2W3X4Y5Z6A7B8', N'AHI0M46', 6);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'9C0D1E2F3G4H5I6J7', N'BIJ1N57', 7);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'5K6L7M8N9P0Q1R2S3', N'CJK2O68', 8);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'1T2U3V4W5X6Y7Z8A9', N'DKL3P79', 9);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'6B7C8D9E0F1G2H3I4', N'ELM4Q80', 10);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'2J3K4L5M6N7P8Q9R0', N'FMN5R91', 1);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'7S8T9U0V1W2X3Y4Z5', N'GNO6S02', 2);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'3A4B5C6D7E8F9G0H1', N'HPO7T13', 3);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'8I9J0K1L2M3N4P5Q6', N'IPQ8U24', 4);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'4R5S6T7U8V9W0X1Y2', N'JQR9V35', 5);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'0Z1A2B3C4D5E6F7G8', N'KRS0W46', 6);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'5H6I7J8K9L0M1N2P3', N'LST1X57', 7);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'1Q2R3S4T5U6V7W8X9', N'MTU2Y68', 8);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'6Y7Z8A9B0C1D2E3F4', N'NUV3Z79', 9);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'2G3H4I5J6K7L8M9N0', N'OVW4A80', 10);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'7P8Q9R0S1T2U3V4W5', N'PXY5B91', 1);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'3X4Y5Z6A7B8C9D0E1', N'QYZ6C02', 2);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'8F9G0H1I2J3K4L5M6', N'RZA7D13', 3);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'4N5P6Q7R8S9T0U1V2', N'SAB8E24', 4);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'0W1X2Y3Z4A5B6C7D8', N'TBC9F35', 5);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'9E0F1G2H3I4J5K6L7', N'UCD0G46', 6);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'5M6N7P8Q9R0S1T2U3', N'VDE1H57', 7);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'1V2W3X4Y5Z6A7B8C9', N'WEF2I68', 8);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'6D7E8F9G0H1I2J3K4', N'XFG3J79', 9);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'2L3M4N5P6Q7R8S9T0', N'YGH4K80', 10);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'7U8V9W0X1Y2Z3A4B5', N'ZHI5L91', 1);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'3C4D5E6F7G8H9I0J1', N'AJI6M02', 2);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'8K9L0M1N2P3Q4R5S6', N'BJK7N13', 3);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'4T5U6V7W8X9Y0Z1A2', N'CKL8O24', 4);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'0B1C2D3E4F5G6H7I8', N'DLM9P35', 5);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'9A1K2L3M4N5P6Q7R8', N'EMN0Q46', 6);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'5T7U8V9W1X2Y3Z4A1', N'FOP1R57', 7);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'1B3C4D5E7F8G9H1I2', N'GPQ2S68', 8);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'6J8K9L1M2N3P5Q6R3', N'HQR3T79', 9);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'2S4T5U7V8W9X1Y2Z4', N'IRS4U80', 10);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'7A9B1C2D4E5F6G8H5', N'JST5V91', 1);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'3I5J6K8L9M1N2P4Q6', N'KTL6W02', 2);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'8R0S1T3U4V5W7X8Y7', N'LUM7X13', 3);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'4Z6A7B9C1D2E3F5G8', N'MVN8Y24', 4);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'0H2I3J5K6L7M8N0P9', N'NWO9Z35', 5);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'9Q1R2S4T5U6V7W9X0', N'OXY0A46', 6);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'5Y7Z8A0B1C2D3E6F1', N'PYZ1B57', 7);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'1G3H4I6J7K8L9M2N2', N'QZA2C68', 8);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'6P8Q9R1S2T3U4V7W3', N'RAA3D79', 9);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'2X4Y5Z7A8B9C1D3E4', N'SBB4D80', 10);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'7F9G1H2I3J4K5L8M5', N'TCC5F91', 1);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'3N5P6Q8R9S1T2U4V6', N'UDD6G02', 2);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'8W0X1Y3Z4A5B6C9D7', N'VEE7H13', 3);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'4E6F7G9H1I2J3K5L8', N'WFF8I24', 4);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'0M2N3P5Q6R7S8T1U9', N'XGG9J35', 5);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'9V1W2X4Y5Z6A7B0C0', N'YHH0K46', 6);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'5D7E8F0G1H2I3J6K1', N'ZII1L57', 7);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'1L3M4N6P7Q8R9S2T2', N'AJA2M68', 8);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'6U8V9W1X2Y3Z4A7B3', N'BKB3N79', 9);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'2C4D5E7F8G9H1I3J4', N'CLC4O80', 10);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'7K9L1M2N3P4Q5R8S5', N'DMD5P91', 1);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'3T5U6V8W9X1Y2Z4A6', N'ENE6Q02', 2);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'8B0C1D3E4F5G6H9I7', N'FOG7R13', 3);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'4J6K7L9M1N2P3Q5R8', N'GPH8S24', 4);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'0S2T3U5V6W7X8Y1Z9', N'HQI9T35', 5);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'9A1B2C4D5E6F7G0H0', N'IRJ0U46', 6);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'5I7J8K0L1M2N3P6Q1', N'JSK1V57', 7);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'1R3S4T6U7V8W9X2Y2', N'KTL2W68', 8);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'6Z8A9B1C2D3E4F7G3', N'LUM3X79', 9);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'2H4I5J7K8L9M1N3P4', N'MVN4Y80', 10);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'7Q9R1S2T3U4V5W8X5', N'NWO5Z91', 1);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'3Y5Z6A8B9C1D2E4F6', N'PXN6A02', 2);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'8G0H1I3J4K5L6M9N7', N'QYQ7B13', 3);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'4P6Q7R9S1T2U3V5W8', N'RZR8C24', 4);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'0X2Y3Z5A6B7C8D1E9', N'SAB9D35', 5);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'9F1G2H4I5J6K7L0M0', N'TBC0E46', 6);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'5O7P8Q0R1S2T3U6V1', N'UCD1F57', 7);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'1W3X4Y6Z7A8B9C2D2', N'VDE2G68', 8);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'6E8F9G1H2I3J4K7L3', N'WEF3H79', 9);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'2M4N5P7Q8R9S1T3U4', N'XFG4I80', 10);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'7V9W1X2Y3Z4A5B8C5', N'YGH5J91', 1);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'3D5E6F8G9H1I2J4K6', N'ZHI6K02', 2);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'8L0M1N3P4Q5R6S9T7', N'AJI7L13', 3);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'4U6V7W9X1Y2Z3A5B8', N'BJK8M24', 4);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'0C2D3E5F6G7H8I1J9', N'CKL9N35', 5);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'9K1L2M4N5P6Q7R0S0', N'DMD0P46', 6);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'5S7T8U0V1W2X3Y6Z1', N'ENE1Q57', 7);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'1A3B4C6D7E8F9G2H2', N'FOG2R68', 8);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'6I8J9K1L2M3N4P7Q3', N'GPH3S79', 9);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'2R4S5T7U8V9W1X3Y4', N'HQI4T80', 10);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'7Z9A1B2C3D4E5F8G5', N'IRJ5U91', 1);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'3H5I6J8K9L1M2N4P6', N'JSK6V02', 2);
INSERT INTO MOTOS_MOTTU (CHASSI, PLACA, ID_MODELO) VALUES (N'8Q0R1S3T4U5V6W9X7', N'KTL7W13', 3);

-- Comentários sobre os dados inseridos
-- ============================================================================
-- Pátios: 12 registros distribuídos por diferentes cidades brasileiras
-- Usuários: 12 registros vinculados aos pátios
-- Carrapatos: 15 registros com diferentes status de bateria e uso (CodigoSerial limitado a 7 chars)
-- Motos: 15 registros vinculados aos pátios e carrapatos (Placa limitada a 7 chars)
-- Modelos Mottu: 10 modelos diferentes
-- Motos Mottu: 120+ registros com placas de 7 caracteres
-- ============================================================================
